// Profile-only UI. The existing account service owns balance and purchases.
import {currencyName} from './park-economy.js';
export function createProfileWallet(doc,api){
 const el=(tag,cls,text)=>{const n=doc.createElement(tag);n.className=cls;if(text)n.textContent=text;return n};
 const root=el('section','profile-wallet park-ui-card'),title=el('h3','','Your wallet'),balance=el('strong','profile-wallet-balance','Loading…'),badges=el('strong','profile-wallet-badges'),note=el('p'),claim=el('button','profile-wallet-claim'),retry=el('button','profile-wallet-retry','Retry balance'),status=el('p','profile-wallet-status'),history=el('details','profile-wallet-history'),summary=el('summary','','Recent rewards & purchases'),entries=el('ul');history.append(summary,entries);
 root.setAttribute('aria-label','Park wallet');balance.setAttribute('aria-live','polite');status.setAttribute('role','status');claim.type=retry.type='button';claim.hidden=retry.hidden=true;root.append(title,balance,badges,note,claim,retry,status,history);
 let closed=false,pending=false,loading=false;
 function render(){if(closed)return;const p=api.get();balance.textContent=p?`${p.inventory.coins.toLocaleString('en-US')} Six Seven Coins`:'Loading…';badges.textContent=p?`${(p.inventory.badges||0).toLocaleString('en-US')} Fashion Badges`:'';const test=p?.testCoins;claim.hidden=!test;claim.disabled=pending||test?.claimed===true;claim.textContent=pending?'Adding test coins…':test?.claimed?'Test coins received':`Get ${test?.amount?.toLocaleString('en-US')||'1,000'} test coins`;note.textContent='Six Seven Coins → 67 Coins shop. Fashion Badges → Badge shop. Earn badges in Daily tasks, matches and Pip’s parcel jobs. No real-money top-up or automatic exchange.';root.setAttribute('aria-busy',String(pending||loading));entries.replaceChildren(...(p?.walletHistory||[]).slice(-8).reverse().map(row=>el('li','',`${row.amount>0?'+':''}${row.amount} ${currencyName(row.currency)} · ${row.reason} · ${new Date(row.at).toLocaleDateString('en-US')}`)));history.hidden=!entries.children.length}
 async function load(){if(loading||closed)return;loading=true;retry.hidden=true;status.textContent='';render();try{await api.load()}catch(e){if(!closed){status.textContent=e.message||'Your balance could not load.';retry.hidden=false}}finally{loading=false;render()}}
 claim.addEventListener('click',async()=>{if(pending||closed||api.get()?.testCoins?.claimed)return;pending=true;status.textContent='';render();try{await api.claim();if(!closed)status.textContent='Test coins added. Open Shop to choose your items.'}catch(e){if(!closed)status.textContent=e.message||'Coins could not be added. Please retry.'}finally{pending=false;render()}});
 retry.addEventListener('click',load);const unsubscribe=api.subscribe(render);render();void load();return{element:root,dispose(){closed=true;unsubscribe?.()}};
}
